### ISSUE TITLE
Music stops streaming at times

### ISSUE THREAD

**Issue by NathanWong1106** [NathanWong1106/NoodleBot-Public-Version#2]
**Describe the bug**
At random intervals, audio streamed from youtube to a voice channel may cut out.

**To Reproduce**
1. Type '-join' to get the bot to join your voice channel
2. Use '-play [song]' to add a song to the queue
3. Queue up several songs or put a song on loop
4. Sometimes, the songs may cut off. Otherwise, it will work as expected

**Expected behavior**
Audio streams from youtube without breaking off.

**Additional context**
So far, I have found no common occurrences between user input and the bug. It seems to occur randomly? It is most likely a problem in my usage of ytdl-core. The bot must leave and rejoin the voice channel in order for music to start streaming again.

**Logs**
2020-04-21T01:07:04.043750+00:00 app[worker.1]: Error: input stream: Error parsing config: Unexpected token ; in JSON at position 42978
2020-04-21T01:07:04.043761+00:00 app[worker.1]: at gotConfig (/app/node_modules/ytdl-core/lib/info.js:125:11)
2020-04-21T01:07:04.043761+00:00 app[worker.1]: at exports.getBasicInfo (/app/node_modules/ytdl-core/lib/info.js:79:18)
2020-04-21T01:07:04.043762+00:00 app[worker.1]: at runMicrotasks (<anonymous>)
2020-04-21T01:07:04.043762+00:00 app[worker.1]: at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-04-21T01:07:04.043763+00:00 app[worker.1]: at async Object.exports.<computed> [as getBasicInfo] (/app/node_modules/ytdl-core/lib/info.js:314:18)
2020-04-21T01:07:04.043763+00:00 app[worker.1]: at async exports.getFullInfo (/app/node_modules/ytdl-core/lib/info.js:187:14)
2020-04-21T01:07:04.043764+00:00 app[worker.1]: at async Object.exports.<computed> [as getFullInfo] (/app/node_modules/ytdl-core/lib/info.js:314:18)

**Comment by NathanWong1106** [comment]
The issue should be fixed after updating `ytdl-core` to the newest version 2.1.0
